// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// EmailService is an autogenerated mock type for the EmailService type
type EmailService struct {
	mock.Mock
}

type EmailService_Expecter struct {
	mock *mock.Mock
}

func (_m *EmailService) EXPECT() *EmailService_Expecter {
	return &EmailService_Expecter{mock: &_m.Mock}
}

// SendWelcomeEmail provides a mock function with given fields: ctx, email, name
func (_m *EmailService) SendWelcomeEmail(ctx context.Context, email string, name string) error {
	ret := _m.Called(ctx, email, name)

	if len(ret) == 0 {
		panic("no return value specified for SendWelcomeEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, email, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EmailService_SendWelcomeEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendWelcomeEmail'
type EmailService_SendWelcomeEmail_Call struct {
	*mock.Call
}

// SendWelcomeEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - name string
func (_e *EmailService_Expecter) SendWelcomeEmail(ctx interface{}, email interface{}, name interface{}) *EmailService_SendWelcomeEmail_Call {
	return &EmailService_SendWelcomeEmail_Call{Call: _e.mock.On("SendWelcomeEmail", ctx, email, name)}
}

func (_c *EmailService_SendWelcomeEmail_Call) Run(run func(ctx context.Context, email string, name string)) *EmailService_SendWelcomeEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *EmailService_SendWelcomeEmail_Call) Return(_a0 error) *EmailService_SendWelcomeEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EmailService_SendWelcomeEmail_Call) RunAndReturn(run func(context.Context, string, string) error) *EmailService_SendWelcomeEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewEmailService creates a new instance of EmailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmailService(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmailService {
	mock := &EmailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
