// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "go-usersvc-demo/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// UserCache is an autogenerated mock type for the UserCache type
type UserCache struct {
	mock.Mock
}

type UserCache_Expecter struct {
	mock *mock.Mock
}

func (_m *UserCache) EXPECT() *UserCache_Expecter {
	return &UserCache_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, id
func (_m *UserCache) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserCache_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type UserCache_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *UserCache_Expecter) Delete(ctx interface{}, id interface{}) *UserCache_Delete_Call {
	return &UserCache_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *UserCache_Delete_Call) Run(run func(ctx context.Context, id int64)) *UserCache_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *UserCache_Delete_Call) Return(_a0 error) *UserCache_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserCache_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *UserCache_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *UserCache) Get(ctx context.Context, id int64) (*domain.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type UserCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *UserCache_Expecter) Get(ctx interface{}, id interface{}) *UserCache_Get_Call {
	return &UserCache_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *UserCache_Get_Call) Run(run func(ctx context.Context, id int64)) *UserCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *UserCache_Get_Call) Return(_a0 *domain.User, _a1 error) *UserCache_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserCache_Get_Call) RunAndReturn(run func(context.Context, int64) (*domain.User, error)) *UserCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, user
func (_m *UserCache) Set(ctx context.Context, user *domain.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type UserCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
func (_e *UserCache_Expecter) Set(ctx interface{}, user interface{}) *UserCache_Set_Call {
	return &UserCache_Set_Call{Call: _e.mock.On("Set", ctx, user)}
}

func (_c *UserCache_Set_Call) Run(run func(ctx context.Context, user *domain.User)) *UserCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.User))
	})
	return _c
}

func (_c *UserCache_Set_Call) Return(_a0 error) *UserCache_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserCache_Set_Call) RunAndReturn(run func(context.Context, *domain.User) error) *UserCache_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserCache creates a new instance of UserCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserCache {
	mock := &UserCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
