// Code generated by protoc-gen-go. DO NOT EDIT.
// Manually maintained to avoid protoc dependency.
// source: proto/user.proto

package pb

import (
	"google.golang.org/protobuf/runtime/protoimpl"
)

// Ensure these types satisfy the interface (compile-time check).
var _ protoimpl.MessageState

// User represents the user entity in protobuf.
type User struct {
	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email     string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt string `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt string `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

type CreateUserRequest struct {
	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

type GetUserByIDRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

type ListUsersRequest struct {
	Page  int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

type ListUsersResponse struct {
	Data  []*User `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total int64   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page  int32   `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit int32   `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
}

type UpdateUserRequest struct {
	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
}

type DeleteUserRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

type DeleteUserResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

type UserResponse struct {
	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email     string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt string `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt string `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

// ProtoMessage stubs to satisfy proto.Message interface.
func (x *User) ProtoMessage()               {}
func (x *CreateUserRequest) ProtoMessage()  {}
func (x *GetUserByIDRequest) ProtoMessage() {}
func (x *ListUsersRequest) ProtoMessage()   {}
func (x *ListUsersResponse) ProtoMessage()  {}
func (x *UpdateUserRequest) ProtoMessage()  {}
func (x *DeleteUserRequest) ProtoMessage()  {}
func (x *DeleteUserResponse) ProtoMessage() {}
func (x *UserResponse) ProtoMessage()       {}

func (x *User) Reset()               {}
func (x *CreateUserRequest) Reset()  {}
func (x *GetUserByIDRequest) Reset() {}
func (x *ListUsersRequest) Reset()   {}
func (x *ListUsersResponse) Reset()  {}
func (x *UpdateUserRequest) Reset()  {}
func (x *DeleteUserRequest) Reset()  {}
func (x *DeleteUserResponse) Reset() {}
func (x *UserResponse) Reset()       {}

func (x *User) String() string               { return x.Name }
func (x *CreateUserRequest) String() string  { return x.Email }
func (x *GetUserByIDRequest) String() string { return "" }
func (x *ListUsersRequest) String() string   { return "" }
func (x *ListUsersResponse) String() string  { return "" }
func (x *UpdateUserRequest) String() string  { return "" }
func (x *DeleteUserRequest) String() string  { return "" }
func (x *DeleteUserResponse) String() string { return x.Message }
func (x *UserResponse) String() string       { return x.Name }
